Models/Data/Seed.cs
using Microsoft.EntityFrameworkCore;
using suggestionbox.Data;
using System;

namespace suggestionbox.Models.Data
{
    public static class Seed
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new suggestionboxContext(
                serviceProvider.GetRequiredService<DbContextOptions<suggestionboxContext>>()))
            {
                SeedSuggestionType(context);
            }
        }

        public static void SeedSuggestionType(suggestionboxContext context)
        {
            if (context.SuggestionType.Any())
            {
                return;   // SuggestionType has already been seeded
            }

            context.SuggestionType.AddRange(
                new SuggestionType
                {
                    name = "suggestie",
                    description = ""
                },
                new SuggestionType
                {
                    name = "uitje",
                    description = "",
                    require_daterange = true
                }
            );

            context.SaveChanges();
        }
    }
}

Models/ErrorViewModel.cs
namespace suggestionbox.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Suggestion.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.Extensions.Hosting;
using System.ComponentModel.DataAnnotations;

namespace suggestionbox.Models
{
    public class Suggestion
    {
        public int id { get; set; }
        public string subject { get; set; }
        public string description { get; set; }
        public int? userId { get; set; }
        public string? userName { get; set; }

        public int suggestionTypeId { get; set; }
        [ValidateNever] //TODO this is currently needed because data isnt sent correctly from frontend. Consider use of viewmodels or building the list from scratch
        public SuggestionType suggestionType { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime startDate { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime endDate { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime? deleted_At { get; set; }

        public string[]? categories { get; set; }
    }
}

Models/SuggestionType.cs
using System.ComponentModel.DataAnnotations;

namespace suggestionbox.Models
{
    public class SuggestionType
    {
        public int id { get; set; }

        public string name { get; set; }

        public string description { get; set; }

        public bool require_daterange { get; set; }

        public ICollection<Suggestion> suggestions { get; } = new List<Suggestion>();
    }
}

Controllers/SuggestionsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using suggestionbox.Data;
using suggestionbox.Models;

namespace suggestionbox.Controllers
{
    public class SuggestionsController : Controller
    {
        private readonly suggestionboxContext _context;

        public SuggestionsController(suggestionboxContext context)
        {
            _context = context;
        }

        // GET: Suggestions
        public async Task<IActionResult> Index()
        {
            var list = await _context.Suggestion.Where(a => a.deleted_At == null).ToListAsync();
            foreach(var item in list)
            {
                var f = 1;
            }
            return View(list);
        }

        // GET: Suggestions/Create
        public async Task<IActionResult> Create()
        {
            var list = await _context.SuggestionType.ToListAsync();
            ViewData["typelist"] = list.ConvertAll(a =>
            {
                return new SelectListItem()
                {
                    Text = a.name,
                    Value = a.id.ToString(),
                    Selected = false
                };
            });

            return View();
        }

        //TODO  This is obviously not the way to go. The frontend is currently sending the data in a different way from plain JSON, causing arguements to not bind corretly.
        //      The current workaround is making two functions calling the same functionality. This needs to be fixed.
        [HttpPost]
        public async Task<IActionResult> Create([Bind("id,subject,description,userId,userName,suggestionTypeId,startDate,endDate,categories")] Suggestion suggestion)
        {
            return await createSuggestion(suggestion);
        }

        [HttpPost]
        public async Task<IActionResult> CreateDup([FromBody] Suggestion suggestion)
        {
            return await createSuggestion(suggestion);
        }

        private async Task<IActionResult> createSuggestion(Suggestion suggestion)
        {
            suggestion.suggestionType = _context.SuggestionType.FirstOrDefault(a => a.id == suggestion.suggestionTypeId);

            if (ModelState.IsValid)
            {
                _context.Add(suggestion);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Suggestions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var suggestion = await _context.Suggestion
                .FirstOrDefaultAsync(m => m.id == id);
            if (suggestion == null)
            {
                return NotFound();
            }

            return View(suggestion);
        }

        // POST: Suggestions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var suggestion = await _context.Suggestion.FindAsync(id);
            if (suggestion != null)
            {
                suggestion.deleted_At = DateTime.Now;
                _context.Suggestion.Update(suggestion);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SuggestionExists(int id)
        {
            return _context.Suggestion.Any(e => e.id == id);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Suggestionbox</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/suggestionbox.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <partial name="_Navbar.cshtml" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">Suggestion Box</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Suggestions" asp-action="Index">Suggesties</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Suggestions" asp-action="Create">Maak Suggestie</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

Views/Suggestions/Create.cshtml
@model suggestionbox.Models.Suggestion

@{
    ViewData["Title"] = "Create";
    var list = (List<SelectListItem>)ViewData["typelist"];
}

<h1>Create</h1>

<h4>Suggestion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Onderwerp</label>
                <input asp-for="subject" class="form-control" required/>
                <span asp-validation-for="subject" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label class="control-label">Beschrijving</label>
                <input asp-for="description" class="form-control" required/>
                <span asp-validation-for="description" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label class="control-label">Gebruiker Id</label>
                <input asp-for="userId" type="number" class="form-control" />
                <span asp-validation-for="userId" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label class="control-label">Gebruikersnaam</label>
                <input asp-for="userName" class="form-control" />
                <span asp-validation-for="userName" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label class="control-label">Suggestie type</label>
                <select asp-for="suggestionTypeId" class="form-control" asp-items="@list" required></select>
                <span asp-validation-for="suggestionTypeId" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label class="control-label">Start datum</label>
                <input asp-for="startDate" class="form-control" />
                <span asp-validation-for="startDate" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label class="control-label">Eind datum</label>
                <input asp-for="endDate" class="form-control" />
                <span asp-validation-for="endDate" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label class="control-label">Categorieën</label>
                <input asp-for="categories" class="form-control" />
                <span asp-validation-for="categories" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Suggestions/Delete.cshtml
@model suggestionbox.Models.Suggestion

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Suggestion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.subject)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.userId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.userId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.userName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.userName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GetType().Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GetType().Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.startDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.startDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.endDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.endDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.categories)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.categories)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Suggestions/Index.cshtml
@model IEnumerable<suggestionbox.Models.Suggestion>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Onderwerp
            </th>
            <th>
                Beschrijving
            </th>
            <th>
                GebruikerId
            </th>
            <th>
                Gebruiker
            </th>
            <th>
                Type
            </th>
            <th>
                Begindatum
            </th>
            <th>
                Einddatum
            </th>
            <th>
                Duur
            </th>
            <th>
                Categorieën
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.subject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.userId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.userName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.suggestionTypeId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.startDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.endDate)
            </td>
            <td>
                @Math.Round(((item.endDate - item.startDate).TotalDays), 2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.categories)
            </td>
            <td>
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>